### ISSUE TITLE
Lag when use the plug-in in a UE5 build

### ISSUE THREAD

**Issue by zoniia** [HAL9HARUKU/MopUE4#10]
I use the plug-in in a UE5 projet, it works perfectly in editor but when I build so projet, during the exe it has some lag. The squeletton update with a delay et it is buggy. Have you any idea of the problem ?

**Comment by zoniia** [comment]
It s because of the ThreeDPoseTracker.exe, if the window is not focus it lag

**Comment by sbyintech** [comment]
I did a project with Unreal and ThreeDPoseTracker and had to run them on two different computers so they were both the focused program.
