### ISSUE TITLE
Tried in UE5, receives Error message

### ISSUE THREAD

**Issue by ScioEstasPotenco** [HAL9HARUKU/MopUE4#2]

**Comment by ScioEstasPotenco** [comment]
I have tried to use in Unreal Engine 5. The problem is that I receive this error message: 
LogOSC: Warning: Failed to parse OSCBundle of invalid format. #bundle identifier not first item in packet.

**Comment by HAL9HARUKU** [comment]
Sorry, it's not yet compatible with UE5.
Thank you for reporting.

**Comment by ScioEstasPotenco** [comment]
I solved the issue. Thank you,
